// AUTO-GENERATED by scripts/copy-sounds-to-public.ts. DO NOT edit by hand.
// Source files: data/sounds/<category>/*.mp3 for each named category.
// Add or remove there; the prebuild/predev hook regenerates this file.
//
// At runtime, focus-shell's audio-ticker picks one URL at random per session
// from WARNING_SOUND_URLS and plays it as a one-shot when the per-question
// target elapses (see SPEC §6.12). The post-session shell picks one URL at
// random from FAILURE_SOUND_URLS / ALMOST_SOUND_URLS / SUCCESS_SOUND_URLS
// based on the user's raw score on a full_length / simulation session and
// plays it once on mount.

const WARNING_SOUND_URLS: readonly string[] = [
	"/audio/warning/boom.mp3",
	"/audio/warning/bruh.mp3",
	"/audio/warning/error.mp3",
	"/audio/warning/faaah.mp3",
	"/audio/warning/oh-my-god.mp3",
	"/audio/warning/steve-ouch.mp3"
]

const FAILURE_SOUND_URLS: readonly string[] = [
	"/audio/failure/4chan.mp3",
	"/audio/failure/bob-esponja.mp3",
	"/audio/failure/danger-alarm-sound-effect-meme.mp3",
	"/audio/failure/dun-dun-dun.mp3",
	"/audio/failure/fail.mp3",
	"/audio/failure/huh.mp3",
	"/audio/failure/mungus.mp3",
	"/audio/failure/oh-no.mp3",
	"/audio/failure/omg-bruh-oh-hell-nah.mp3"
]

const ALMOST_SOUND_URLS: readonly string[] = [
	"/audio/almost/got-you.mp3",
	"/audio/almost/here-we-go-again.mp3",
	"/audio/almost/mission-failed.mp3"
]

const SUCCESS_SOUND_URLS: readonly string[] = [
	"/audio/success/can-we-get-much-higher.mp3",
	"/audio/success/children-yaysound-effect.mp3",
	"/audio/success/deja-vu.mp3",
	"/audio/success/epic-sax.mp3",
	"/audio/success/gas-gas-gas.mp3",
	"/audio/success/jojos-golden-wind.mp3",
	"/audio/success/oh-my-god-meme.mp3",
	"/audio/success/sicko-mode.mp3",
	"/audio/success/snoop_dog.mp3",
	"/audio/success/wow.mp3",
	"/audio/success/yippee.mp3"
]

export { ALMOST_SOUND_URLS, FAILURE_SOUND_URLS, SUCCESS_SOUND_URLS, WARNING_SOUND_URLS }
