#!/usr/bin/env bun

// EXEMPT FROM THE PROJECT RULESET. Native console.log / try/catch etc.
//
// Regenerate src/config/sound-bank.ts from the static MP3 files in
// public/audio/<category>/. public/audio IS the source of truth — the
// script does NOT copy or move files. The manifest is regenerated from
// the on-disk listing so app code can import a typed, per-category URL
// array. Runs from `bun dev` (predev) and `bun build` (prebuild).
//
// Filename note: kept as `copy-sounds-to-public.ts` for compatibility
// with the package.json predev/prebuild hooks. No copy actually happens
// anymore; the script's contract is "emit the manifest" only.
//
// Categories enumerated (each must be a subdirectory of public/audio):
//   - warning   → focus-shell urgency sample (per-question target)
//   - failure   → post-session result, raw score 0..29
//   - almost    → post-session result, raw score 30..39
//   - success   → post-session result, raw score 40..50

import { readdirSync, writeFileSync } from "node:fs"
import { basename, join, resolve } from "node:path"

const projectRoot = resolve(import.meta.dirname, "..")
const publicRoot = join(projectRoot, "public", "audio")
const manifestPath = join(projectRoot, "src", "config", "sound-bank.ts")

interface CategoryConfig {
	dirName: string
	exportName: string
}

const CATEGORIES: ReadonlyArray<CategoryConfig> = [
	{ dirName: "warning", exportName: "WARNING_SOUND_URLS" },
	{ dirName: "failure", exportName: "FAILURE_SOUND_URLS" },
	{ dirName: "almost", exportName: "ALMOST_SOUND_URLS" },
	{ dirName: "success", exportName: "SUCCESS_SOUND_URLS" }
]

function listMp3sIn(dir: string): string[] {
	const entries = readdirSync(dir, { withFileTypes: true })
	const out: string[] = []
	for (const entry of entries) {
		if (entry.isFile() && entry.name.endsWith(".mp3")) {
			out.push(entry.name)
		}
	}
	out.sort()
	return out
}

interface CategoryResult {
	exportName: string
	urls: string[]
}

function processCategory(category: CategoryConfig): CategoryResult {
	const srcDir = join(publicRoot, category.dirName)
	let entries: string[] = []
	try {
		entries = listMp3sIn(srcDir)
	} catch (err) {
		console.warn(
			`[regen-sound-bank] WARNING: public/audio/${category.dirName}/ not found; emitting empty bank for ${category.exportName}`
		)
		console.warn(
			`[regen-sound-bank]          ${err instanceof Error ? err.message : String(err)}`
		)
		return { exportName: category.exportName, urls: [] }
	}
	if (entries.length === 0) {
		console.warn(
			`[regen-sound-bank] WARNING: no *.mp3 files in public/audio/${category.dirName}/`
		)
	} else {
		console.log(
			`[regen-sound-bank]   public/audio/${category.dirName}/: found ${entries.length} file(s)`
		)
	}
	const urls = entries.map(function toUrl(name) {
		return `/audio/${category.dirName}/${basename(name)}`
	})
	return { exportName: category.exportName, urls }
}

function writeManifest(results: ReadonlyArray<CategoryResult>): void {
	const lines: string[] = []
	lines.push("// AUTO-GENERATED by scripts/copy-sounds-to-public.ts. DO NOT edit by hand.")
	lines.push("// Source files: public/audio/<category>/*.mp3 for each named category.")
	lines.push("// Add or remove there; the prebuild/predev hook regenerates this file.")
	lines.push("//")
	lines.push("// At runtime, focus-shell's audio-ticker picks one URL at random per session")
	lines.push("// from WARNING_SOUND_URLS and plays it as a one-shot when the per-question")
	lines.push("// target elapses (see SPEC §6.12). The post-session shell picks one URL at")
	lines.push("// random from FAILURE_SOUND_URLS / ALMOST_SOUND_URLS / SUCCESS_SOUND_URLS")
	lines.push("// based on the user's raw score on a full_length / simulation session and")
	lines.push("// plays it once on mount.")
	lines.push("")
	for (const result of results) {
		lines.push(`const ${result.exportName}: readonly string[] = [`)
		// Biome's formatter rejects a trailing comma on the last array
		// element here, so emit the final entry without one. (The
		// per-category section is rendered as one const-decl + one
		// blank line.)
		const lastIdx = result.urls.length - 1
		for (let i = 0; i < result.urls.length; i++) {
			const url = result.urls[i]
			if (url === undefined) continue
			const tail = i === lastIdx ? "" : ","
			lines.push(`\t"${url}"${tail}`)
		}
		lines.push("]")
		lines.push("")
	}
	// Biome's organizeImports rule sorts the export names alphabetically;
	// emit them sorted so the generated file is idempotent under
	// `biome check --write`.
	const sortedExportNames = results
		.map(function pickName(r) {
			return r.exportName
		})
		.slice()
		.sort()
	lines.push(`export { ${sortedExportNames.join(", ")} }`)
	lines.push("")
	writeFileSync(manifestPath, lines.join("\n"))
	console.log(
		`  wrote ${manifestPath} with categories: ${results
			.map(function summarize(r) {
				return `${r.exportName}=${r.urls.length}`
			})
			.join(", ")}`
	)
}

function main(): void {
	console.log("[regen-sound-bank] enumerating public/audio/<category>/*.mp3")
	const results: CategoryResult[] = []
	for (const category of CATEGORIES) {
		const result = processCategory(category)
		results.push(result)
	}
	writeManifest(results)
	console.log("[regen-sound-bank] done")
}

main()
